Repository nanoframework/System.Net.WebSockets, pull requests merged in 2022-01, with the labels that each got.

#20 Add integration for WebsocketServer with HttpListner
  System.Net.WebSockets.Server.nuspec
  System.Net.WebSockets.nuspec
  WebSockets.Client/System.Net.WebSockets.Client.nfproj
  WebSockets.Client/packages.config
  WebSockets.Server/System.Net.WebSockets.Server.nfproj
  WebSockets.Server/packages.config
  WebSockets/ClientWebSocket/ClientWebSocket.cs
  WebSockets/System.Net.WebSockets.nfproj
  WebSockets/WebSocket.cs
  WebSockets/WebSocketServer/WebSocketClientsPool.cs
  WebSockets/WebSocketServer/WebSocketServer.cs
  WebSockets/WebSocketServer/WebSocketServerClient.cs
  WebSockets/WebSocketServer/WebSocketServerOptions.cs
  WebSockets/packages.config
  nanoframework.System.Net.Websockets.sln
Labels: Type: dependencies, Type: enhancement

#21 Added support for Sec-WebSocket-Protocol
  WebSockets/WebSocketServer/WebSocketServer.cs
Labels: Type: enhancement

#22 Added support for custom Http Headers for Websocket
  WebSockets.Client/System.Net.WebSockets.Client.nfproj
  WebSockets/ClientWebSocket/ClientWebSocket.cs
  WebSockets/ClientWebSocket/ClientWebSocketHeaders.cs
  WebSockets/System.Net.WebSockets.nfproj
  WebSockets/WebSocket.cs
Labels: Type: bug, Type: enhancement

#30 Fixing nuget names
  README.md
  azure-pipelines.yml
  nanoframework.System.Net.WebSockets.Client.nuspec
  nanoframework.System.Net.WebSockets.Server.nuspec
  nanoframework.System.Net.WebSockets.nuspec
Labels: Type: Documentation, Area: Config-and-Build
